### ISSUE TITLE
Forced alignments files without matching wav files

### ISSUE THREAD

**Issue by lucasondel** [besacier/mboshi-french-parallel-corpus#2]
Hi,

I've found that there some forced alignments files in [forced_alignments_supervised_spkr/all](https://github.com/besacier/mboshi-french-parallel-corpus/tree/master/forced_alignments_supervised_spkr/all) that do not match any audio files in [full_corpus_newsplit/all](https://github.com/besacier/mboshi-french-parallel-corpus/tree/master/full_corpus_newsplit/all). I think it would be better to remove them as it's easier to prepare the features/alignments for any ASR toolkit.

Lucas

**Comment by pierregodard** [comment]
did you pull since yesterday? i cleaned the forced_alignments_supervised_spkr directory last night.

**Comment by lucasondel** [comment]
My mistake, I didn't update my repository before to check this.
